/**
 * Tokenises every string the Era I output window can render and writes them to
 * `tokens.generated.ts`. Run with `bun run gen:era1-highlight` from `apps/web`.
 *
 * This file imports Shiki and is never bundled — nothing in the client tree
 * imports it. The output is committed so the browser gets tokens, not a
 * highlighter, and so a stream cannot flicker: colours computed from finished
 * text stay put as the text is revealed.
 *
 * The fingerprint below only catches a source string changing. It cannot
 * catch a `shiki` version bump changing grammars or themes underneath the
 * committed tokens — no test can detect that drift, so re-run
 * `bun run gen:era1-highlight` by hand after any `shiki` upgrade.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { createHighlighter } from "shiki";
import { PROMPTS } from "../completions";
import {
  type CompletionToken,
  fingerprintSources,
  kindFromScopes,
  type PrefixToken,
} from "./index";

const THEMES = { dark: "github-dark", light: "github-light" } as const;
const BANDS = ["low", "mid", "high"] as const;

const highlighter = await createHighlighter({
  langs: ["javascript"],
  themes: [THEMES.light, THEMES.dark],
});

function tokenise(code: string) {
  return highlighter
    .codeToTokens(code, {
      includeExplanation: "scopeName",
      lang: "javascript",
      themes: THEMES,
    })
    .tokens.flatMap((line, index) => {
      const withNewline = index === 0 ? line : [{ content: "\n" }, ...line];
      return withNewline as {
        content: string;
        explanation?: { scopes: { scopeName: string }[] }[];
        htmlStyle?: Record<string, string>;
      }[];
    });
}

function prefixTokens(code: string): PrefixToken[] {
  return tokenise(code).map((t) => {
    const scopes = t.explanation?.[0]?.scopes.map((s) => s.scopeName) ?? [];
    return {
      d: t.htmlStyle?.["--shiki-dark"] ?? "#E1E4E8",
      k: kindFromScopes(scopes),
      l: t.htmlStyle?.color ?? "#24292E",
      t: t.content,
    };
  });
}

function completionTokens(code: string): CompletionToken[] {
  return tokenise(code).map((t) => ({
    k: kindFromScopes(t.explanation?.[0]?.scopes.map((s) => s.scopeName) ?? []),
    t: t.content,
  }));
}

const prefixes: Record<string, PrefixToken[]> = {};
const completions: Record<string, CompletionToken[]> = {};

for (const prompt of PROMPTS) {
  prefixes[prompt.id] = prefixTokens(prompt.prefix);
  for (const band of BANDS) {
    completions[`${prompt.id}:base:${band}`] = completionTokens(
      prompt.continuations[band]
    );
    completions[`${prompt.id}:instruct:${band}`] = completionTokens(
      prompt.instructAnswers[band]
    );
  }
}

const body = `// GENERATED by highlight/generate.ts — do not edit by hand.
// Regenerate with: bun run gen:era1-highlight
import type { CompletionToken, PrefixToken } from "./index";

export const SOURCE_FINGERPRINT = ${JSON.stringify(fingerprintSources(PROMPTS))};

export const PREFIX_TOKENS: Record<string, PrefixToken[]> = ${JSON.stringify(prefixes, null, 2)};

export const COMPLETION_TOKENS: Record<string, CompletionToken[]> = ${JSON.stringify(completions, null, 2)};
`;

writeFileSync(join(import.meta.dir, "tokens.generated.ts"), body);
process.stdout.write(
  `wrote ${Object.keys(prefixes).length} prefixes, ${Object.keys(completions).length} completions\n`
);
